name: 'Agora build and push'

on:
  workflow_dispatch:
  merge_group:
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Git secrets setup
        run: |
          git clone https://github.com/awslabs/git-secrets.git ~/git-secrets
          cd ~/git-secrets
          git checkout ad82d68ee924906a0401dfd48de5057731a9bc84
          sudo make install
        shell: bash

      - name: Secrets check
        run: |
          sudo ln -s "$(which echo)" /usr/local/bin/say
          ./minnie-kenny.sh --force
          git secrets --scan-history
        shell: bash

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Bump the tag to a new version
        uses: databiosphere/github-actions/actions/bumper@bumper-0.0.6
        id: tag
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }} # this allows the push to succeed later
          RELEASE_BRANCHES: develop
          WITH_V: true

      - name: Construct Dockerhub and GCR image names
        id: image-name
        run: |
          echo "DOCKERHUB_NAME=broadinstitute/agora:${{ steps.tag.outputs.new_tag }}" >> $GITHUB_OUTPUT
          echo "GCR_NAME=gcr.io/broad-dsp-gcr-public/agora:${{ steps.tag.outputs.new_tag }}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t ${{ steps.image-name.outputs.DOCKERHUB_NAME }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: dsdejenkins
          password: ${{ secrets.DSDEJENKINS_DOCKERHUB_PASSWORD }}

      - name: Push dockerhub image
        run: docker push ${{ steps.image-name.outputs.DOCKERHUB_NAME }}
