name: dsp-appsec-trivy
on:
  pull_request:
  schedule:
    - cron: '0 14 * * 1' # each Monday at 9am EST

jobs:
  appsec-trivy:
    # Parse Dockerfile and build, scan image if a "blessed" base image is not used
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          sarif: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ !github.base_ref }} # omit upload on PRs
        with:
          sarif_file: trivy-results.sarif

       - name: Notify in Slack
        if: failure()
        uses: broadinstitute/action-slack@v3.15.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          channel: "trivy-weekly-scans-notblessedimages"
          username: "Agora Trivy scan"
          icon_emoji: ':alert_red_light:'
          text: 'Agora Trivy scan failure. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here> to see the run.'
