name: 'Agora unit tests'

on:
  workflow_dispatch: #Manual trigger from GitHub UI
  push:
  merge_group:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Checkout the Agora repo
      - name: Git secrets setup
        run: |
          git clone https://github.com/awslabs/git-secrets.git ~/git-secrets
          cd ~/git-secrets
          git checkout ad82d68ee924906a0401dfd48de5057731a9bc84
          sudo make install
        shell: bash
      - name: Secrets check
        run: |
          sudo ln -s "$(which echo)" /usr/local/bin/say
          ./minnie-kenny.sh --force
          git secrets --scan-history
        shell: bash
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Run tests
        run: |
          docker pull mongo:4.4
          docker pull testcontainersofficial/ryuk:0.3.0
          ./minnie-kenny.sh --force
          git secrets --scan-history
          sbt clean coverage test coverageReport
